module.exports = [
  {
    name: "Leanne Graham",
    username: "Bret",
    company: "Romaguera-Crona",
    company_description: "Multi-layered client-server neural-net",
    commercial_register: "harnessrealmarkets",
    address: "Kulas Light Apt. 556, Gwenborough",
    email: "Sincere@april.biz",
    phone: "982654357",
    logo: "https://i0.wp.com/lamiradafotografia.es/wp-content/uploads/2014/07/foto-perfil-psicologo-180x180.jpg?resize=180%2C180",
    enable: true,
  },
  {
    name: "Robert Pickman",
    username: "Rob",
    company: "Great Company City",
    company_description: "The first company of the citynetwork",
    commercial_register: "RobJobMarket",
    address: "Av Manco Capac, Calle 13, Colombia",
    email: "robpick@gmail.com",
    phone: "982654357",
    logo: "https://i0.wp.com/thehappening.com/wp-content/uploads/2017/07/foto-perfil-5.jpg?resize=1024%2C694&ssl=1",
    enable: true,
  },
  {
    name: "Raquel Montgomery",
    username: "Mony",
    company: "Montgomery Club",
    company_description: "The top club of the city",
    commercial_register: "Mostful experience",
    address: "Hight Avenue 523, Londres",
    email: "raquelmont@gmail.com",
    phone: "982654357",
    logo: "https://economia3.com/wp-content/uploads/2019/12/Natalia-Juarranz-EQUIPO-HUMANO.jpg",
    enable: true,
  }
];